### ISSUE TITLE
Invalid Database host error

### ISSUE THREAD

**Issue by ohchloeho** [sredevopsorg/ghost-on-kubernetes#408]
I'm getting 500: Invalid database host error in my K3s cluster despite using the right hosts. 

My config.production.json:
```
{
  "url": "https://yourdomain.tld",
  "admin": {
    "url": "https://yourdomain.tld"
  },
  "server": {
    "port": 2368,
    "host": "0.0.0.0"
  },
  "mail": {
    "transport": "SMTP",
    "from": "user@server.com",
    "options": {
      "service": "Google",
      "host": "smtp.gmail.com",
      "port": 465,
      "secure": true,
      "auth": {
        "user": "user@server.com",
        "pass": "passsword"
      }
    }
  },
  "logging": {
    "transports": [
      "stdout"
    ]
  },
  "database": {
    "client": "mysql",
    "connection": 
    {
      "host": "ghost-on-kubernetes-mysql-service",
      "user": "mysql-db-user",
      "password": "mysql-db-password",
      "database": "mysql-db-name",
      "port": "3306"
    }
  },
  "process": "local",
  "paths": {
    "contentPath": "/home/nonroot/app/ghost/content"
  }
}
```

My mysql-config.yaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: ghost-on-kubernetes-mysql-env
  namespace: ghost-on-kubernetes
  labels:
    app: ghost-on-kubernetes-mysql
    app.kubernetes.io/name: ghost-on-kubernetes-mysql-env
    app.kubernetes.io/instance: ghost-on-kubernetes
    app.kubernetes.io/version: '5.92'
    app.kubernetes.io/component: database-secret
    app.kubernetes.io/part-of: ghost-on-kubernetes
    
type: Opaque
stringData:
  MYSQL_DATABASE: mysql-db-name
  MYSQL_USER: mysql-db-user
  MYSQL_PASSWORD: mysql-db-password
  MYSQL_ROOT_PASSWORD: mysql-db-root-password
  MYSQL_HOST: '%'
```

My Ghost Pod logs:
```
INFO Ghost is running in production...
[2025-03-16 03:00:08] INFO Your site is now available on https://yourdomain.tld/
[2025-03-16 03:00:08] INFO Ctrl+C to shut down
[2025-03-16 03:00:08] INFO Ghost server started in 0.445s
[2025-03-16 03:00:19] ERROR Invalid database host.

Invalid database host.

"Please double check your database config."
```

I've tried to change the '%' to match the hostname on my config.production.json, and i still get the pod crashing. I'm unable to see what the issue is with the database host, i just get error 500.

I've checked that there's no network policies blocking the connection, and my mysql pod shell only lets me connect to the mysql instance with the ` -h localhost ` flag
